/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/**/*.blade.php",
        "./resources/**/**/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/**/*.vue",
        "./resources/**/**/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                black: "#000000",
                white: "#FFFFFF",
                offwhite: "#FBFAFA",
                grey: "#D4D7D8",
                orange: "#FF7432",
                blue: "#27353D",
                green: "#C4C6B5",
                "sec-green": "#ACBCAA",
                "tri-green": "#8EA59B",
                lightgrey: "#F4F5F5",
                newwhite: "#F2F2F2",
                bronze: "#CD7F32",
                bruin: "#6a2305",
                goud: "#FFD700",
                blauw: "#0000FF",
                groen: "#008000",
                beige: "#dbaf6e",
                'primary-50': 'rgb(var(--primary-50))',
                'primary-100': 'rgb(var(--primary-100))',
                'primary-200': 'rgb(var(--primary-200))',
                'primary-300': 'rgb(var(--primary-300))',
                'primary-400': 'rgb(var(--primary-400))',
                'primary-500': 'rgb(var(--primary-500))',
                'primary-600': 'rgb(var(--primary-600))',
                'primary-700': 'rgb(var(--primary-700))',
                'primary-800': 'rgb(var(--primary-800))',
                'primary-900': 'rgb(var(--primary-900))',
                'primary-950': 'rgb(var(--primary-950))',
                'surface-0': 'rgb(var(--surface-0))',
                'surface-50': 'rgb(var(--surface-50))',
                'surface-100': 'rgb(var(--surface-100))',
                'surface-200': 'rgb(var(--surface-200))',
                'surface-300': 'rgb(var(--surface-300))',
                'surface-400': 'rgb(var(--surface-400))',
                'surface-500': 'rgb(var(--surface-500))',
                'surface-600': 'rgb(var(--surface-600))',
                'surface-700': 'rgb(var(--surface-700))',
                'surface-800': 'rgb(var(--surface-800))',
                'surface-900': 'rgb(var(--surface-900))',
                'surface-950': 'rgb(var(--surface-950))'
            },
            fill: {
                current: "currentColor",
            },
            fill: (theme) => ({
                orange: "#FF7432",
                white: "#FFFFFF",
            }),
            backgroundImage: {
                "hero-image": 'url("../public/img/heroauto.webp")',
                info: 'url("../../public/img/bg-info2.webp")',
                "info-2": 'url("../../public/img/info.webp")',
                "hero-image-2": 'url("../../public/img/overonsbg.webp")',
            },
            screens: {
                xs: "475px",
            },
            spacing: {
                "6/7": "85%",
            },
        },
        fontFamily: {
            roboto: ["Roboto", "sans-serif"],
        },
    },
    plugins: [],
};
